version: 2
jobs: 
  build:
    docker:
      - image: circleci/ruby:2.6.3
    # steps:
    #  - checkout 
    #  - run: echo "A first hello"

      - image: circleci/postgres:9.4.12-alpine

    working_directory: ~rails_tutorial/taskeleaf
  test: 
    steps:
      - checkout
      - name: Restore bundle cache 
      - key: taskleaf-{{ checksum "Gemfile.lock" }}

      - run: bundle install --path vendor/bundle 
      
      - name: Store bundle cache
      - key: taskleaf-{{ checksum "Gemfile.lock" }}
      
      - run:
          name: bundle install
          no_output_timeout: 15m
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
  
  # deploy: 
    # docker:
      # - image: circleci/ruby:2.6.1-node-browsers
    # working_directory: ~/rails_turorial/taskleaf
    # steps:
      # - checkout
      # - run:
          # name: 'Install Heroku CLI, if necessary'
          # command: |
            # if [[ $(command -v heroku) == "" ]]; then
              # curl https://cli-assets.heroku.com/install.sh | sh
            # else
              # echo "Heroku is already installed. No operation was performed."
            # fi
      # - run:
          # name: heroku maintenance on
          # command: heroku maintenance:on --app ${HEROKU_APP_NAME_STAGE}
      # - run:
          # name: Deploy to Heroku_Staging
          # command: |
            # git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STAGE.git master
      # - run:
          # name: heroku maintenance off
          # command: heroku maintenance:on --app ${HEROKU_APP_NAME_STAGE}

  workflows: 
  　version: 2
   jobs:
     - build 
     - test
  #  - deploy: 
  #    requires: 
  #      - build
  #      - test
  #    fileters:
  #      branches: 
  #      only: 
  #        - master